title = "Spring3g"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"
themesDir = "./themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Go to the sea, if you would fish well."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/duyunqiang"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/notebook.jpg"
  recent_posts_number = 2
